language: ruby
before_install:
  - gem install bundler
before_script:
  - rake db:migrate
script:
  - rake ci
rvm:
  - 2.2.5
  - 2.3.1
gemfile:
  - test/gemfiles/Gemfile.rails.5.0
  - test/gemfiles/Gemfile.rails.5.1
branches:
  only:
    - master
    - happy-production
matrix:
  fast_finish: true
  include:
    - rvm: 2.3.1
      gemfile: test/gemfiles/Gemfile.rails.master
  allow_failures:
    - gemfile: test/gemfiles/Gemfile.rails.master
